nombre = input("introduce tu nombre: ")
apellido = input("introduce tu apellido: ")
edad = input("introduce tu edad: ")
ciudad = input("introduce tu ciudad: ")
print(f"hola , {nombre}  {apellido} {edad} años de la ciudad de {ciudad} . Bienvenido a Generetion.")